package com.monopoly.domain.engine.enums;

public enum HandleType {
    BUY_PRPRTY, CHANCE, CHNG_RENT, GO_PRSN, PAY_RENT, SALE_CARD, STAR_MOVE, TREASURY, UPGRD_PRPTY, FREE_PRSN_CARD,
    STRT_PLR_MOVE, END_PLR_MOVE, STRT_GAME, END_GAME, ROLL_DICE
}
